### ISSUE TITLE
Problem with output

### ISSUE THREAD

**Issue by overthink** [Fikayo/ListingMatcher#1]
Hi Fikayo,

I was trying to evaluate your solution but there is a problem with the output format. Please make sure each line in the output file is a Result object as described on http://sortable.com/challenge/, i.e.

```
{
  "product_name": String
  "listings": Array[Listing]
}

```

An example line in the output file should look like:

```
{"listings": [{"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Red)"}, {"currency": "USD", "price": "189.00", "manufacturer": "CASIO", "title": "Casio Exilim EX-FC150 10.1MP High Speed Digital Camera with 5x Optical Zoom, CMOS Shift Image Stabilization & 2.7-inch LCD (Red)"}, {"currency": "USD", "price": "249.00", "manufacturer": "CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD (Black)"}], "product_name": "Casio_Exilim_EX-FC150"}
```

In your case the value of the `price` property on Listing objects is output as a number rather than a string.  If you could change your code to output `price` as a string, I'd be happy to take another look at your submission.

Thanks!

Mark (from sortable.com)

**Comment by Fikayo** [comment]
Hello Mark,

I have modified the code to reflect the necessary changes.
However, I was initially looking for a co-op position this Winter. Given
that Sortable is looking for a full time position, I will no longer be able
to work at Sortable. I will  also be in school during the Summer and so
will be indisposed.
I am very sorry for the confusion.

Sincerely,
Odunayo Fikayo

Hi Fikayo,

I was trying to evaluate your solution but there is a problem with the
output format. Please make sure each line in the output file is a Result
object as described on http://sortable.com/challenge/, i.e.

{
  "product_name": String
  "listings": Array[Listing]
}

An example line in the output file should look like:

{"listings": [{"currency": "USD", "price": "189.00", "manufacturer":
"CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera
with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD
(Red)"}, {"currency": "USD", "price": "189.00", "manufacturer":
"CASIO", "title": "Casio Exilim EX-FC150 10.1MP High Speed Digital
Camera with 5x Optical Zoom, CMOS Shift Image Stabilization & 2.7-inch
LCD (Red)"}, {"currency": "USD", "price": "249.00", "manufacturer":
"CASIO", "title": "Casio EX-FC150 10.1MP High Speed Digital Camera
with 5x Zoom with CMOS Shift Image Stabilization and 2.7 inch LCD
(Black)"}], "product_name": "Casio_Exilim_EX-FC150"}

In your case the value of the price property on Listing objects is output
as a number rather than a string. If you could change your code to output
price as a string, I'd be happy to take another look at your submission.

Thanks!

Mark (from sortable.com)

—
Reply to this email directly or view it on GitHub
https://github.com/Fikayo/ListingMatcher/issues/1.

**Comment by overthink** [comment]
That's ok.  I'll email you the results of your challenge anyway.
